// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EmsContext))]
    [Migration("20260607101727_Editsonvies")]
    partial class Editsonvies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Calculated.Historical.LineAnalysis", b =>
                {
                    b.Property<decimal>("AdjustedAvailability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.ToTable("LineAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.LineHourlyAnalysis", b =>
                {
                    b.Property<decimal>("AdjustedAvailability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.ToTable("LineHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.TransformerAnalysis", b =>
                {
                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("TransformerAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.TransformerHourlyAnalysis", b =>
                {
                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("TransformerHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.ZoneAnalysis", b =>
                {
                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransformerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ZoneAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.ZoneHourlyAnalysis", b =>
                {
                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransformerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ZoneHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_LineAnalysis", b =>
                {
                    b.Property<decimal>("AdjustedAvailability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VW_LineAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_LineHourlyAnalysis", b =>
                {
                    b.Property<decimal>("AdjustedAvailability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VW_LineHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_TransformerAnalysis", b =>
                {
                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("VW_TransformerAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_TransformerHourlyAnalysis", b =>
                {
                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("VW_TransformerHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_ZoneAnalysis", b =>
                {
                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransformerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VW_ZoneAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_ZoneHourlyAnalysis", b =>
                {
                    b.Property<decimal>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransformerId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VW_ZoneHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Transformer", "Definitions");
                });

            modelBuilder.Entity("DAL.Models.Definitions.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RatioFromParent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TransformerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("TransformerId");

                    b.ToTable("Zones", "Definitions");
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmail")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Identity.PasswordResetOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAttempt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("DAL.Models.Identity.SystemClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SystemClaims", "Identity");
                });

            modelBuilder.Entity("DAL.Models.RealTime.Energy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgCurrent")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPact")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPapp")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPowerFactor")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPreact")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgVoltage")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("Fault")
                        .HasColumnType("int");

                    b.Property<decimal>("I1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("I2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("I3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumEnergy")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalEnergyConsumptionDiff")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V3")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.ToTable("Energy", "RealTime");
                });

            modelBuilder.Entity("DAL.Models.RealTime.MachineLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPending")
                        .HasColumnType("bit");

                    b.Property<string>("JobOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SKU")
                        .HasColumnType("int");

                    b.Property<string>("SKUCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKUName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineLoads", "RealTime");
                });

            modelBuilder.Entity("DAL.Models.RealTime.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CountDiff")
                        .HasColumnType("int");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<int>("Fault")
                        .HasColumnType("int");

                    b.Property<string>("Functionality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qreject")
                        .HasColumnType("int");

                    b.Property<int>("QrejectDiff")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Speed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Signals", "RealTime");
                });

            modelBuilder.Entity("DAL.Models.Threshold.EnergyHeatmapThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("HighFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HighTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LowFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediumFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MediumTo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EnergyHeatmapThresholds");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factories", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatioFromParent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Lines", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.LineTransformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("TransformerId");

                    b.ToTable("LineTransformers", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faunctionality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDominant")
                        .HasColumnType("bit");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RatedSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Machines", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.MachineShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedQty")
                        .HasColumnType("int");

                    b.Property<int?>("RejectedQty")
                        .HasColumnType("int");

                    b.Property<int?>("SKUId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("SKUId");

                    b.ToTable("MachineShifts", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.SKU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CartonSize")
                        .HasColumnType("int");

                    b.Property<string>("JobOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackSize")
                        .HasColumnType("int");

                    b.Property<int?>("PallSize")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SkuCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicalSKU")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("SKUs", "Definitions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Factory", "factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("factory");
                });

            modelBuilder.Entity("DAL.Models.Definitions.Zone", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Factory", "Factory")
                        .WithMany("Zones")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Definitions.Transformer", "Transformer")
                        .WithMany("Zones")
                        .HasForeignKey("TransformerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factory");

                    b.Navigation("Transformer");
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("DAL.Models.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.RealTime.MachineLoad", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Machine", "Machine")
                        .WithMany("MachineLoad")
                        .HasForeignKey("MachineId");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("DAL.Models.RealTime.Signal", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Factory", "Factory")
                        .WithMany("Lines")
                        .HasForeignKey("FactoryId");

                    b.HasOne("DAL.Models.Definitions.Zone", "Zone")
                        .WithMany("Lines")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factory");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Domain.Models.Definitions.LineTransformer", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Line", "Line")
                        .WithMany("LineTransformers")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Definitions.Transformer", "Transformer")
                        .WithMany("LineTransformers")
                        .HasForeignKey("TransformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Transformer");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Machine", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Line", "Line")
                        .WithMany("Lines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Domain.Models.Definitions.MachineShift", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Machine", "Machine")
                        .WithMany("MachineShifts")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Definitions.SKU", "SKU")
                        .WithMany("MachineShifts")
                        .HasForeignKey("SKUId");

                    b.Navigation("Machine");

                    b.Navigation("SKU");
                });

            modelBuilder.Entity("Domain.Models.Definitions.SKU", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.Navigation("LineTransformers");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("DAL.Models.Definitions.Zone", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Factory", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.Navigation("LineTransformers");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Machine", b =>
                {
                    b.Navigation("MachineLoad");

                    b.Navigation("MachineShifts");
                });

            modelBuilder.Entity("Domain.Models.Definitions.SKU", b =>
                {
                    b.Navigation("MachineShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
