// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EmsContext))]
    [Migration("20260524092402_AddViewsAndCalculatedTabels")]
    partial class AddViewsAndCalculatedTabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Auth.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.TransformerAnalysis", b =>
                {
                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("TransformerAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Historical.TransformerHourlyAnalysis", b =>
                {
                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("TransformerHourlyAnalysis", "Calculated");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_TransformerAnalysis", b =>
                {
                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("VW_TransformerAnalysis", "RealTime");
                });

            modelBuilder.Entity("DAL.Models.Calculated.Views.VW_TransformerHourlyAnalysis", b =>
                {
                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hermonics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HourStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalEnergyConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("VW_TransformerHourlyAnalysis", "RealTime");
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("TransformerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Transformer", "Definitions");
                });

            modelBuilder.Entity("DAL.Models.RealTime.Energy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgCurrent")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPact")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPapp")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPowerFactor")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgPreact")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgTHDi")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgTHDv")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("AvgVoltage")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("DiffEnergy3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Energy3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<int?>("Fault")
                        .HasColumnType("int");

                    b.Property<decimal>("I1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("I2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("I3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("PF3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Pact3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Papp3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Preact3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumEnergy")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDi3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("THDv3")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalEnergyConsumptionDiff")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V1")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V2")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("V3")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.ToTable("Energy", "RealTime");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factories", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Lines", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.LineTransformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("TransformerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("TransformerId");

                    b.ToTable("LineTransformers", "Definitions");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Machines", "Definitions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Factory", "factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("factory");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Factory", "Factory")
                        .WithMany("Lines")
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Domain.Models.Definitions.LineTransformer", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Line", "Line")
                        .WithMany("LineTransformers")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Definitions.Transformer", "Transformer")
                        .WithMany("LineTransformers")
                        .HasForeignKey("TransformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Transformer");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Machine", b =>
                {
                    b.HasOne("Domain.Models.Definitions.Line", null)
                        .WithMany("Lines")
                        .HasForeignKey("LineId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DAL.Models.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Definitions.Transformer", b =>
                {
                    b.Navigation("LineTransformers");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Factory", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Models.Definitions.Line", b =>
                {
                    b.Navigation("LineTransformers");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
